### PR TITLE
Package Logo

### PR DESCRIPTION
**Pull request by colbyfayock**
Thought I'd take a shot at fulfilling the request for a new logo per https://github.com/PaulLeCam/react-leaflet/issues/434.

What I've put together:
* **A logo**: kind of the obvious path of combining the React logo and the Leaflet logo. The leaflet logo is simplified to make it sit a little better. The color is pretty much a between blend of the react and leaflet logo colors. The typeface is Open Sans, so something that can easily be used as a webfont on the site and other uses.
* **Placement**: Updates the homepage to include the logo in the title space. Are there any other spots I should consider?
* **Colors**: Used the colors from the logo to update the website scheme, particularly the primary and secondary colors

Here's the logo in all of it's glory:
react-leaflet-logo-white-1000x280

And here's a little package of an EPS, SVG, the JPG above, and a transparent PNG.
[react-leaflet-logo.zip](https://github.com/PaulLeCam/react-leaflet/files/3721037/react-leaflet-logo.zip)

The nice thing about the logo is I think the icon could easily be used standalone, would make a nice die-cut sticker 😉 

Excited to hear what you think!

### CODE REVIEW

**Comment by PaulLeCam** [comment]
Looks great, thanks!

Could you add a license in this PR, the README and/or the website please so it's clear how the logo could be used?

Also, please feel free to add credit information with a link of your choice if you want, maybe in the website footer or another place you find relevant?

Thanks!

**Comment by colbyfayock** [comment]
added a page with a few blurbs and some "do not"'s. in the sidebar, should now see Usage > Logo & Branding. i haven't put together a page like this before and i haven't used docasaurus before, so warning, may want to make sure i did that right and everything makes sense :) particularly, the one thing i wasn't sure about was managing the `md` file between the various sidebar files, originally tried adding the 1 ID to all, but that didnt seem to work right

**Comment by PaulLeCam** [comment]
Thanks!
Could you please also add a license, such as [Creative Commons](https://creativecommons.org/choose/) or whichever suits you best, so it's clear how the logo and assets can be used?

**Comment by colbyfayock** [comment]
done! went with the default CC license, did you prefer to have the license stored in the repo or are you good linking to it? went with a link like their example on that page

**Comment by PaulLeCam** [comment]
A link as you added is all good, thanks!

**Comment by colbyfayock** [comment]
i just realized, was i supposed to build and publish this to the gh page?

**Comment by PaulLeCam** [comment]
No, you need write access to do this. I'll publish the updated website soon with the new release.

**Pull request merged**
