### PR TITLE
Fix Polyline propTypes validation

### PR DESCRIPTION
**Pull request by zemadz**
Fixes https://github.com/PaulLeCam/react-leaflet/issues/366

### CODE REVIEW

**Comment by PaulLeCam** [comment]
Sorry I don't get what you're trying to do... The `latlngList` is already an `arrayOf(latng)`, see https://github.com/PaulLeCam/react-leaflet/blob/master/src/propTypes/latlngList.js#L7 so I don't see in what way your PR is changing anything.

**Comment by zemadz** [comment]
True, `latlngList.js` is `arrayOf(latlng)`, but the import was previously `import latlngList from './propTypes/latlng'` (should have imported `./propTypes/latlng`).

I didn't know/notice that there is a `latlngList.js`, will change my fix to use that.

**Comment by PaulLeCam** [comment]
Ah yes good catch!
Yes if you can please update your PR to fix the import should be good to go.

**Comment by PaulLeCam** [comment]
Should be fixed in v1.6.4

**Pull request closed without merging**
