### PR TITLE
Add support for event handlers on Map

### PR DESCRIPTION
**Pull request by andywer**
Support attaching DOM event listeners to the <Map /> using React properties.

For instance:

```javascript
<Map onClick={myHandler} />
```

### CODE REVIEW

**Comment by PaulLeCam** [comment]
Hi,
Leaflet event handlers can be attached to the `Map` using the `onLeaflet` prefix (https://github.com/PaulLeCam/react-leaflet#events), but not the DOM ones.
Is there any use case it would be an absolute necessity to bind DOM events?

**Comment by andywer** [comment]
Hi Paul,
we are currently using the handlers onDragOver (just for event.preventDefault()) and onDrop to enable dragging objects from outside into the map. This doesn't work using the Leaflet event handlers (since Leaflet handles d&d in a way that doesn't suite our needs).

Cheers,
Andy

**Comment by PaulLeCam** [comment]
Hi Andy,
Thanks for the context.

At the moment I'm still unsure whether DOM events should be supported or only Leaflet ones.
The Leaflet ones are prefixed with `onLeaflet` so they wouldn't clash with DOM ones in the props, but at the same time my concern is that attaching both DOM and Leaflet events could lead to confusing behaviors.
The only case I've had where DOM events would be useful is on the Map, as in your case, and what I did was simply to wrap the Map in another component to handle these events, do you think this would work for you?

At some point I'd like to simply set the Leaflet events as `on...` rather than  `onLeaflet...`, any suggestion?

**Comment by andywer** [comment]
Yeah, thanks for the hint. The mark-up doesn't look as clean now, but I totally understand your point.
Your idea of changing the listener property names from `onLeaflet...` to `on...` sounds good to me.

Cheers

**Pull request closed without merging**
