### PR TITLE
Update Marker.js

### PR DESCRIPTION
**Pull request by tomaszkepa**
Accept divIcon in icon prop.

### CODE REVIEW

**Comment by PaulLeCam** [comment]
Do you get any warning when using a divIcon?
If so, could you please provide a reproducible example?

**Comment by tomaszkepa** [comment]
```js
Warning: Failed propType: Invalid prop `icon` supplied to `Marker`, expected instance of `<<anonymous>>`. Check the render method of `EventMap`.
```

```js
import React, { Component, PropTypes } from 'react';
import reactMixin from 'react-mixin';
import { ReactScriptLoaderMixin } from 'react-script-loader';
import { Map, Marker, TileLayer } from 'react-leaflet';

class EventMap extends Component {

  static propTypes = {
    latitude: PropTypes.number.isRequired,
    longitude: PropTypes.number.isRequired,
  };

  constructor(props) {
    super(props);

    this.state = {
      scriptLoading: true,
      scriptLoadError: false,
    };
  }

  onScriptLoaded() {
    this.setState({scriptLoading: false});
  }

  onScriptError() {
    this.setState({scriptLoading: false, scriptLoadError: true});
  }

  getScriptURL() {
    return '//cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js';
  }

  render() {
    let renderMap = null;
    const position = [this.props.latitude, this.props.longitude];
    const zoom = 14;

    if (!this.state.scriptLoading && !this.state.scriptLoadError) {
      const Leaflet = window.L;

      renderMap = (
        <Map center={position} zoom={zoom} minZoom={zoom - 3} maxZoom={zoom + 2}>
          <TileLayer
            url="http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png"
            attribution="&copy; <a href=&quot;http://osm.org/copyright&quot; target=&quot;_blank&quot;>OpenStreetMap</a> contributors, &copy; <a href=&quot;http://cartodb.com/attributions&quot; target=&quot;_blank&quot;>CartoDB</a>"
            />
          <Marker position={position} icon={Leaflet.divIcon()}/>
        </Map>
      );
    }

    return renderMap;
  }
}

reactMixin(EventMap.prototype, ReactScriptLoaderMixin);

export default EventMap;
```

**Comment by PaulLeCam** [comment]
You seem to be loading Leaflet with a script loader, while it should already be installed as a peer dependency of react-leaflet, so I assume your error comes from having two versions of Leaflet.
I tested it again an I get no warning when creating divIcons using the Leaflet package.

**Comment by tomaszkepa** [comment]
Ok thx you're right.

**Pull request closed without merging**
