### PR TITLE
Animate panning and zooming

### PR DESCRIPTION
**Pull request by mariusandra**
Hey,

I'm in need of a feature where the map pans smoothly (animate=true) when changing the center.

I have made such modifications in this PR, and added an example.

Is this enough to be merged? Anything else I should do?

Thank you!

Marius

### CODE REVIEW

**Comment by PaulLeCam** [comment]
Thanks!

**Comment by mariusandra** [comment]
Thank you for merging! Could you also release a new (patch?) version with this change?

**Comment by PaulLeCam** [comment]
Yes I'll publish a new version this week-end.

**Comment by PaulLeCam** [comment]
@mariusandra I just published v0.10.2 containing you commit, thanks!

**Pull request merged**
