### PR TITLE
Updated MultiPolygon 'polygons' prop to allow polygons with holes

### PR DESCRIPTION
**Pull request by ernoaapa**
Like 'Polygon' already allows passing array of arrays to make holes, also
MultiPolygon should allow it. Even though not read in Leaflet
MultiPolygon documentation, it supports it because Polygon supports it.

### CODE REVIEW

**Comment by PaulLeCam** [comment]
Hi,
Thanks for this PR, do you have a reference of this support by Leaflet please?

**Comment by ernoaapa** [comment]
Oh yeah sure! In Leaflet Polygon documentation http://leafletjs.com/reference.html#polygon it says: 
"You can also create a polygon with holes by passing an array of arrays of latlngs, with the first latlngs array representing the exterior ring while the remaining represent the holes inside."

**Comment by PaulLeCam** [comment]
Thanks!

**Comment by PaulLeCam** [comment]
Released in v0.12.2

**Pull request merged**
