### PR TITLE
Support "flyTo"

### PR DESCRIPTION
**Pull request by jgimbel**
proposed solution to #183

### CODE REVIEW

**Comment by PaulLeCam** [comment]
Thanks!
Could you please remove the code related to generating an `id` for the map? It should not be needed anymore as the `L.map()` factory accepts a `DOMElement` in Leaflet v1.

**Comment by jgimbel** [comment]
Yep. I tried without and it didn't pass the server side render test. Let me double check that I have leaflet 1 and see if that fixes it after the change.

**Comment by jgimbel** [comment]
Please have a look at the Travic CI output. Should the test be updated? It would seem that v1 does not add its own map id in v1 ([source](https://github.com/Leaflet/Leaflet/blob/v1.0.0-rc.2/src/map/Map.js#L710) and [related source](https://github.com/Leaflet/Leaflet/blob/v1.0.0-rc.2/src/dom/DomUtil.js#L17)).

**Comment by PaulLeCam** [comment]
Oh yes sorry I forgot to push an update to the test, should be OK now.

**Comment by PaulLeCam** [comment]
Thanks!

**Pull request merged**
