### PR TITLE
Adds link to old docs

### PR DESCRIPTION
**Pull request by stebogit**
Ref. #812

### CODE REVIEW

**Comment by PaulLeCam** [comment]
Thanks but these are not published anymore.

**Comment by stebogit** [comment]
@PaulLeCam I deployed the docs to allow everybody to access it conveniently, would you mind updating the link on the official site? That's where everybody would look for it.

https://react-leaflet-v2-docs.netlify.app

**Comment by Lorthiz** [comment]
@stebogit examples links are not working. Without that whole doc is less useful.
https://react-leaflet-v2-docs.netlify.app/docs/en/examples -> select any example

**Comment by stebogit** [comment]
@Lorthiz how about now?

**Comment by PaulLeCam** [comment]
> @PaulLeCam I deployed the docs to allow everybody to access it conveniently, would you mind updating the link on the official site? That's where everybody would look for it.
> 
> https://react-leaflet-v2-docs.netlify.app

Thanks, I added a link to the footer of the current website

**Comment by Lorthiz** [comment]
> @Lorthiz how about now?

Looks good, works also on mobile. Thanks for uploading it!

**Pull request closed without merging**
