### PR TITLE
Wrong type mentioned for Map and Marker props center  in the doc /website 

### PR DESCRIPTION
**Pull request by AdiBev**
Map and Marker component props center type is ```LatLng | LatLngLiteral | LatLngTuple```

### CODE REVIEW

**Comment by alecananian** [comment]
What's the issue with the original example? `LatLngTuple` is defined as a tuple of two numbers:

    export type LatLngTuple = [number, number];

**Comment by AdiBev** [comment]
It's the typescript throwing error for this. In index.d.ts file
`export type LatLngTuple = [number, number];`
 this should be `export type LatLngTuple = number[];`

**Comment by alecananian** [comment]
@AdiBev `number[]` would be an array of numbers of any length, while `[number, number]` is an array of only two values, or a tuple.  This is a valid Typescript type: https://www.typescriptlang.org/docs/handbook/basic-types.html#tuple

**Comment by PaulLeCam** [comment]
As commented above, `[number, number]` is an valid position input for Leaflet.
The TS definitions are not defined in this repo so if there is any issue with them please report in the relevant repository.

**Pull request closed without merging**
