### PR TITLE
Update GeoJSON.js

### PR DESCRIPTION
**Pull request by fastlorenzo**
Fixed GeoJson typo (GeoJSON should be GeoJson)

### CODE REVIEW

**Comment by PaulLeCam** [comment]
Thanks for your PR but this is not a typo, `geoJson` has been replaced by `geoJSON` in Leaflet v1 (though the `geoJson` still works as an alias to `geoJSON`).

**Comment by fastlorenzo** [comment]
Hi Paul,

I installed it via npm and received the following error while using geojson: GeoJSON is not a function. After changing the call to GeoJson it worked.
I'll check the version of leaflet when I'm back home and update the thread.

Lorenzo Bernardi

**Comment by PaulLeCam** [comment]
Make sure you are using Leaflet v1+, react-leaflet v1 is not compatible with previous versions.

**Comment by fastlorenzo** [comment]
I checked and the leaflet package (that was installed by another package) was indeed outdated. 
Sorry for the convenience and thanks for that great package!

**Pull request closed without merging**
