### PR TITLE
V1: Fix no elem ref

### PR DESCRIPTION
**Pull request by kontrollanten**
- Update deps
- Remove usage of deprecated lifecycle methods
- Fix handling of `leafletElement` is null or undefined upon unmount

### CODE REVIEW

**Comment by PaulLeCam** [comment]
Thanks but v1 should only get new releases for bug fixes, please use v2 if you want to take advantage of the most recent changes.

**Comment by kontrollanten** [comment]
Can I reopen the PR with only this bug fix https://github.com/PaulLeCam/react-leaflet/pull/485/commits/4c98d88ec01fdfb1c48c1c78b1fc7bce70f5c94c ?

**Comment by PaulLeCam** [comment]
What is the issue?

**Comment by PaulLeCam** [comment]
Could you open another issue with a CodePen or other running example exposing the problem please?

**Comment by kontrollanten** [comment]
I haven't been able to reproduce the error by myself, I've just seen it in my sentry logs

**Comment by PaulLeCam** [comment]
The issue might be caused by something else in your code then, please provide a way to reproduce if you want to get a PR merged.

**Pull request closed without merging**
