### PR TITLE
Draggable Marker example property name fix up.

### PR DESCRIPTION
**Pull request by Dan-Wood**
Hi all

I've fixed a naming mistake on event name property in the Draggable Marker example.

onDragend doesn't exist on MarkerEvents it's ondragend. :)

Cheers
Dan

### CODE REVIEW

**Comment by PaulLeCam** [comment]
Hi,
Thanks but the event names are normalized in the binding logic so case doesn't matter.

**Comment by Dan-Wood** [comment]
Sorry, but this does kind of matter, especially when using Typescript as the build will fail to compile.

Unless I'm doing this wrong, please correct me here.

`
          <Marker
            draggable={true}
            position={this.state.marker}
            ref={this.refmarker}
            onDragend={this.draggedMarker}
            icon={getMapIcon()}
          />
`

> TS2322: Type '{ draggable: true; position: Position; ref: RefObject<Marker<MarkerProps, Marker<any>>>; onDragend: () => void; icon: any; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Marker<MarkerProps, Marker<any>>> & Readonly<{ children?: ReactNode; }> & Readonly<MarkerProps>'.
>   Property 'onDragend' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Marker<MarkerProps, Marker<any>>> & Readonly<{ children?: ReactNode; }> & Readonly<MarkerProps>'.

And obviously

`
          <Marker
            draggable={true}
            position={this.state.marker}
            ref={this.refmarker}
            ondragend={this.draggedMarker}
            icon={getMapIcon()}
          />
`

Works perfectly fine.

**Comment by PaulLeCam** [comment]
These examples are not using TypeScript, so how is this related?
You can use a fully lowercase `ondragend` in your code if it matters to you or your setup.

**Comment by Dan-Wood** [comment]
Regardless,it's the only you showcase or document how to do a draggable marker with react-leaflet.

And leaflet clearly says use dragend.

Surely you can see the confusion there. I don't see why it matters of your examples use typescript or not.

There's no consistency.

**Pull request closed without merging**
